<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

/**
 * PagoCliente records are now generated by ControlRenovacionSeeder
 * as part of the renovation cycle completion flow, ensuring every
 * pago_cliente is properly linked to a historial_renovacion record.
 *
 * This seeder is intentionally empty.
 */
class PagoClienteSeeder extends Seeder
{
    public function run(): void
    {
        // All payment records are created in ControlRenovacionSeeder.
    }
}
